[project]
name = "capy-tui"
version = "0.0.1"
requires-python = ">=3.14.0"
dependencies = "8.2.7"
authors = {name = "capy"}
readme = "README.md"
license = "MIT"

[project.urls]
Repository = "https://github.com/tommyyv/capy_tui.git"
Changelog = "https://github.com/tommyyv/capy_tui/blob/main/CHANGELOG.md"
