[project]
name = "capy-tui"
version = "0.0.1"
authors = [
  { name = "capy" }
]
readme = "README.md"
license = "MIT"
requires-python = ">=3.14.0"
dependencies = [
  "textual==8.2.7"
]

[dependency-groups]
dev = [
  "pytest>=9.1.0"
]

[project.urls]
Repository = "https://github.com/tommyyv/capy_tui.git"
Changelog = "https://github.com/tommyyv/capy_tui/blob/main/CHANGELOG.md"
